### PR TITLE
Remove custom functions from jsoncpp headers

### LINKED ISSUE #1883: Support unmodified JsonCpp
Related to #403. Currently only the bundled JsonCpp library is supported as noted in #1790.

aa58884 made a few modifications to the bundled JsonCpp, which causes compilation against any unmodified version of the library to fail.

We should extract those modifications into our codebase. I'll have a closer look at this.

### PR DESCRIPTION
**Pull request by mkroening**
Resolves #1883.

Most functions where the custom ones were used could be deleted.
The one used instance has been specialized.

### CODE REVIEW

**Comment by quietly-turning** [comment]
This seems fairly straightforward.  Is there anything about this you'd change now, @mwkroening?

**Comment by mkroening** [comment]
I'll rebase on latest upstream, remove the whitespace changes and have another look at the changes, but generally this seems straight forward.

**Comment by quietly-turning** [comment]
> generally this seems straight forward

I agree!  Again, I'm sorry that your pull requests sat unattended as long as they did.

**Comment by mkroening** [comment]
> > generally this seems straight forward
> 
> I agree! Again, I'm sorry that your pull requests sat unattended as long as they did.

No worries!

File: extern/jsoncpp/src/lib_json/json_reader.cpp [hunk 1]
```diff
@@ -877,8 +877,7 @@ std::istream& operator>>( std::istream &sin, Value &root )
     Json::Reader reader;
     bool ok = reader.parse(sin, root, true);
     //JSON_ASSERT( ok );
-//    if (!ok) throw std::runtime_error(reader.getFormatedErrorMessages());
-    assert(ok);
```
Comment (mwkroening) [inline extern/jsoncpp/src/lib_json/json_reader.cpp:881]: This change was not undone in the original version of this PR.
It is more than 10 years old with no comment: https://github.com/stepmania/stepmania/blame/beb793267bfd3927a3bc801c0f03251e0e26caac/src/jsoncpp/src/lib_json/json_reader.cpp

Probably it was introduced to avoid exceptions.
As assert calls abort on failure, the behavior of crashing by not catching this exception should be the same.

Comment (mkroening) [inline extern/jsoncpp/src/lib_json/json_reader.cpp:881]: This change was not undone in the original version of this PR.
It is more than 10 years old with no comment: https://github.com/stepmania/stepmania/blame/beb793267bfd3927a3bc801c0f03251e0e26caac/src/jsoncpp/src/lib_json/json_reader.cpp

Probably it was introduced to avoid exceptions.
As assert calls abort on failure, the behavior of crashing by not catching this exception should be the same.

File: extern/jsoncpp/src/lib_json/json_reader.cpp [hunk 2]
```diff
@@ -1,5 +1,5 @@
-#include "json/reader.h"
-#include "json/value.h"
```
Comment (mkroening) [inline extern/jsoncpp/src/lib_json/json_reader.cpp:2]: This should not be a problem whatsoever, but I am wondering why this was changed initially.

File: extern/jsoncpp/src/lib_json/json_value.cpp [hunk 3]
```diff
@@ -15,7 +15,7 @@
 
 #define JSON_ASSERT_UNREACHABLE assert( false )
 #define JSON_ASSERT( condition ) assert( condition );  // @todo <= change this into an exception throw
-#define JSON_ASSERT_MESSAGE( condition, message ) if (!( condition )) assert(false); /* throw std::runtime_error( message ); */
```
Comment (mkroening) [inline extern/jsoncpp/src/lib_json/json_value.cpp:18]: Similar throw replacement as before.

File: extern/jsoncpp/src/lib_json/json_writer.cpp [hunk 4]
```diff
@@ -111,7 +111,7 @@ std::string valueToString( bool value )
 std::string valueToQuotedString( const char *value )
 {
    // Not sure how to handle unicode...
-   if (strpbrk(value, "\"\\\b\f\n\r\t") == nullptr && !containsControlCharacter( value ))
```
Comment (mkroening) [inline extern/jsoncpp/src/lib_json/json_writer.cpp:114]: This change was done in an automated manner in https://github.com/stepmania/stepmania/commit/ba59dd1656ebb275694d6df443b8c0490e260ba2

Obviously this is equivalent.

File: src/JsonUtil.h [hunk 5]
```diff
@@ -195,57 +197,6 @@ namespace JsonUtil
...
-	static void DeserializeArrayValuesIntoVector(vector<T> &v, const Json::Value &root)
-	{
-		v.clear();
-		for( unsigned i=0; i<root.size(); i++ )
-		{
-			T t;
-			if( root[i].TryGet( t ) )
-				v.push_back( t );
-		}
-	}
```
Comment (mkroening) [inline src/JsonUtil.h:233]: None of the removed functions were used except for this one, specialized with type RString.

File: src/JsonUtil.cpp [hunk 6]
```diff
@@ -75,6 +75,19 @@ bool JsonUtil::WriteFile(const Json::Value &root, const RString &sFile, bool bMi
...
+	for(auto &&inner_value : value)
+	{
+		if(inner_value.isConvertibleTo(Json::stringValue))
+		{
+			values.push_back(inner_value.asString());
+		}
+	}
+	return values;
+}
+
```
Comment (mkroening) [inline src/JsonUtil.cpp:90]: This is the specialized replacement for DeserializeArrayValuesIntoVector.

**Review by mkroening — COMMENTED** [review]
I split the PR in two. First cleanly resetting jsoncpp to vanilla and then removing/replacing affected code.

**Comment by quietly-turning** [comment]
Thank you for the rebase and thorough review!  This seems fine.  With #1883 resolved, would comments like https://github.com/stepmania/stepmania/pull/1790#issuecomment-472653367 be resolved as well?

---

> This should not be a problem whatsoever, but I am wondering why this was changed initially.

[Relevant](https://github.com/stepmania/stepmania/issues?q=label%3A%22it+is+a+mystery+%F0%9F%91%BB%22+).

**Comment by mkroening** [comment]
> Thank you for the rebase and thorough review! This seems fine. With #1883 resolved, would comments like [#1790 (comment)](https://github.com/stepmania/stepmania/pull/1790#issuecomment-472653367) be resolved as well?

Indeed! I'll follow up with an adjustment to the CI. I forgot to add that here.
